### ISSUE TITLE
Excuse me, where can I download the image dataset for gt_2.csv and imu_2.csv

### ISSUE THREAD

**Issue by yangy-98** [MikeS96/vio_quadrotor#3]
Dear Sir,
I'm sorry to bother you.
First thank you very much for providing this repository, it is very helpful for researchers.

When I was learning your repository, I noticed that you provide the gt_2.csv and imu_2.csv in the data folder,
but the image and depth is just test_1, 
I want to continue learning about your repository, could you tell me where I can download the image dataset for gt_2.csv and imu_2.csv?

I look forward to receiving your reply! Thank you very much!

**Comment by MikeS96** [comment]
Hi @yangy-98,

Thank you for your interest on this project. Indeed I had another dataset but I lost it and I do not have it right now. That being said it was almost the same as the one provided. In case you want, you can use this project as a starting point and create your own. 

Best,

**Comment by yangy-98** [comment]
Hi, sir @MikeS96 
Thank you for your reply!
I'm sorry to hear that you've lost another dataset.
But thank you for your advice, and I'll have a try.
